MvcMovie/Models/User.cs
namespace MvcMovie.Models
{
    public class User
    {
        public string? UserName {get; set;}
    }
}

MvcMovie/Controllers/HelloController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class HelloController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }


        public ActionResult ButtonClick(User user)
        {
            return View("HelloUserPage", user);
        }

    }
}

MvcMovie/Views/Hello/HelloUserPage.cshtml
@model MvcMovie.Models.User;
@{
    if (Model.UserName == null)
        Model.UserName = "Anonymous";
    ViewData["Title"] = $"Hello {Model.UserName}!";
}


<div style="max-width: 230px;
     margin: 0 auto;
     position: absolute;
     left:0;
     right:0;
     top: 50%;
     transform:translate(0,-50%);">
    <h1>Hello, @Model.UserName!</h1> 
</div>

MvcMovie/Views/Hello/Index.cshtml
@model MvcMovie.Models.User;
@{
    ViewData["Title"] = "Name";
}

<link rel="stylesheet" href="css/site.css">

<div class="text-center">
    @using(Html.BeginForm("ButtonClick", "Hello"))//Method and Controller
    {
        <h1>Type your name</h1>
        <p><input asp-for="UserName" placeholder="Name"> <button>Send</button></p>
    }
</div>

MvcMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <!--link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcMovie.styles.css" asp-append-version="true" /-->
</head>
<body>
    <!--header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcMovie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header-->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcMovie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script-- src="~/js/site.js" asp-append-version="true"></script-->
   @* @await RenderSectionAsync("Scripts", required: false)*@
</body>
</html>